spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3308/testapp
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true